---
eureka:
  client:
    serviceUrl:
      defaultZone: http://username:password@discovserver-anaplastic-observableness.cfapps.io/eureka


---

spring:
  profiles: cloud
eurika:
    instance:
        hostname: ${vcap.application.uris[0]}
        nonSecurePort: 80
message: this is great
